name: indicMT
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - backcall=0.2.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - cudatoolkit=10.2.89
  - debugpy=1.8.11
  - decorator=5.2.1
  - entrypoints=0.4
  - executing=2.2.0
  - ffmpeg=4.3
  - freetype=2.13.3
  - gmp=6.3.0
  - gnutls=3.6.15
  - htop=3.4.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.14.0
  - ipython=8.4.0
  - jedi=0.19.2
  - jpeg=9e
  - jupyter_client=7.0.6
  - jupyter_core=5.7.2
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnl=3.11.0
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pyzmq=19.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - absl-py==2.3.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.7
    - aiosignal==1.3.2
    - async-timeout==5.0.1
    - attrs==25.3.0
    - blinker==1.9.0
    - click==8.1.8
    - colorama==0.4.6
    - configargparse==1.7.1
    - datasets==3.6.0
    - dill==0.3.8
    - filelock==3.18.0
    - flask==3.1.1
    - frozenlist==1.6.0
    - fsspec==2025.3.0
    - grpcio==1.72.1
    - hf-xet==1.1.2
    - huggingface-hub==0.32.4
    - importlib-metadata==8.7.0
    - itsdangerous==2.2.0
    - jinja2==3.1.6
    - lxml==5.4.0
    - markdown==3.8
    - markupsafe==3.0.2
    - multidict==6.4.4
    - multiprocess==0.70.16
    - opennmt-py==3.0.0
    - pandas==2.2.3
    - portalocker==3.1.1
    - propcache==0.3.1
    - protobuf==6.31.1
    - pyarrow==20.0.0
    - pyonmttok==1.37.1
    - pytz==2025.2
    - pyyaml==6.0.2
    - regex==2024.11.6
    - sacrebleu==2.5.1
    - sentencepiece==0.2.0
    - tabulate==0.9.0
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - tqdm==4.67.1
    - tzdata==2025.2
    - waitress==3.0.2
    - werkzeug==3.1.3
    - xxhash==3.5.0
    - yarl==1.20.0
    - zipp==3.22.0

